export {
  ROWS,
  COLS,
  MAX_ENERGY,
  MERGE_MIN,
  SCORE_FACTOR,
  STATE,
  DIRS,
  MAX_CHAIN_GUARD,
  DEFAULT_SPAWN,
} from './constants.js';
export {
  bfsBlock,
  cloneBoard,
  computeGravity,
  createBoardFilled,
  createCell,
  createEmptyBoard,
  fillEmptySpawn,
  findMaxMin,
  normalizeSpawnOpts,
  pickAutoMerge,
  pickChainCenter,
  pickSpawnAvoiding,
  resetCellIds,
  spawnUpper,
  spawnValue,
  stabilizeBoard,
  applyMerge,
} from './board.js';
export { createGame } from './game.js';
